name: Lefthook

on:
  pull_request:
  push:
    branches:
      - main

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  lefthook:
    uses: FelipeFuhr/ffreis-workflows-general/.github/workflows/general-lefthook.yml@a02d736d25fa99fca8b4b623af9467d7afc472a4
    with:
      working-directory: "."
      go-version-file: "go.mod"
      install-govulncheck: true
      lefthook-bootstrap-command: "make lefthook-bootstrap"
      lefthook-bin: ".bin/lefthook"
      run-pre-push: true
